### PR TITLE
Preceding line is blank

### LINKED ISSUE #5: Incorrectly identifies a line in a function with a preceding empty line as outside the function
Just testing the library with openpyxl in preparation for a Python 3 only release and hit the following bug:

```
    def write_row(self, xf, row, row_idx):

        attrs = {'r': '%d' % row_idx}
```

becomes

```
    def write_row(self, xf, row, row_idx):
attrs = {'r': f"{row_idx}"}
```

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
Resolves #5 

Did some refactoring to isolate what was causing the problem. Generally use pytest for testing but move this to unittest style if required.

### CODE REVIEW

**Comment by jacktasia** [comment]
Thanks for the PR! Sorry for the delayed response I was out of the country without a computer. This looks really good I only have two small concerns:

1. It's unclear to me why the tests aren't passing on python 3.6: https://travis-ci.org/jacktasia/fstringify/builds/528438436

2. `poetry` is really only a dev dependency so I think it would be better to have it separated from the main `requirements.txt`  (in like a `dev_dependencies.txt` and a matching make target) since that's what `setup.py` will use, which means people only installing via `pip` for the cli tool will end up with `poetry`.

**Comment by Themanwithoutaplan** [comment]
Thanks for the reply. No worries about the delay. I'm not that familar with the particular project layout and couldn't find any notes for developers so I just went with what I know.

Out of the box the project doesn't seem to work with tox but I managed to get it running locally by making the requirements explicit.

I then get a test failure in Python3.6 my refactored code:

```
    def test_indent():
        code = """
        def write_row(self, xf, row, row_idx):

            attrs = {'r': '%d' % row_idx}
                """
        lines, scope = no_skipping(code)
>       scoped = scope[2]
E       KeyError: 2
```
This probably explains the test failure. I'll see if I can investigate and fix this.

BTW others at our local sprint have started work on support the `.format()` method.

**Comment by Themanwithoutaplan** [comment]
Looks like strip_scope behaves differently in 3.6:
```
test_process.py(40)test_indent()
-> scoped = scope[2]
(Pdb) scope
{3: {'raw_scope': ["        attrs = {'r': '%d' % row_idx}"], 'strip_scope': <map object at 0x10c2d0828>, 'indent': '        '}}
```

**Comment by Themanwithoutaplan** [comment]
I've added a test for `get_str_bin_op_lines` that also fails with 3.6 and is thus likely to be the culprit.

**Comment by jacktasia** [comment]
> I've added a test for `get_str_bin_op_lines` that also fails with 3.6 and is thus likely to be the culprit.

Thanks. It might be related to `token` enums changing in python 3.7. I think I have a comment there about at least one other being different in 3.7

**Comment by Themanwithoutaplan** [comment]
I think you'll have to use markers rather than hard-coded values. These are the outputs for toknum and tokval for Python 3.7 and 3.6

```
bits = get_str_bin_op_lines(code)
>>> list(bits)
57 utf-8
56

5
1 def
1 write_row
53 (
1 self
53 ,
1 xf
53 ,
1 row
53 ,
1 row_idx
53 )
53 :
4

56

5
1 attrs
53 =
53 {
3 'r'
53 :
3 '%d'
53 %
1 row_idx
53 }
4
```

Python 3.6
```

list(bits)
59 utf-8
58

5
1 def
1 write_row
53 (
1 self
53 ,
1 xf
53 ,
1 row
53 ,
1 row_idx
53 )
53 :
4

5
1 attrs
53 =
53 {
3 'r'
53 :
3 '%d'
53 %
1 row_idx
53 }
4
```

**Comment by Themanwithoutaplan** [comment]
If it's tricky, just dump support for 3.6! ;-) Numbers are in decline anyway.

**Comment by jacktasia** [comment]
> If it's tricky, just dump support for 3.6! ;-) Numbers are in decline anyway.

Yeah, that's pretty tempting.

**Comment by Themanwithoutaplan** [comment]
> > If it's tricky, just dump support for 3.6! ;-) Numbers are in decline anyway.
> 
> Yeah, that's pretty tempting.
I think the different indices at the start are less of a problem than the `56` between the two blocks. This is clearly signifcantly different behaviour between Python versions. 

With regards to actual use: fstringify is really a one-off utility rather than a library (famous last words) so I don't think it would be a huge problem requiring a specific Python version for it.

**Comment by jacktasia** [comment]
> With regards to actual use: fstringify is really a one-off utility rather than a library (famous last words) so I don't think it would be a huge problem requiring a specific Python version for it.

Yeah, I think I am convinced. Feel free to drop the 3.6 part in the travis config or I am happy to push it into this branch whenever you think this is ready to merge.

**Review by jacktasia — APPROVED** [review]
Thanks!

**Comment by Themanwithoutaplan** [comment]
Good to see this merged. This time it was my turn to be out of the country without a computer…

**Pull request merged**
